config/routes.rb
Lemur::Application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  get "sessions/new"
  get "users/new"
  root 'static_pages#home'
  get 'about'	=> 'static_pages#about'
  get 'help'	=> 'static_pages#help'
  get 'terms'	=> 'static_pages#terms'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :show, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/dashboard/_account_settings.html.erb
<div class="dashboard__sidebar--settings-menu">
	<ul>
		<li>
			<%= link_to '<i class="fa fa-cog"></i>Account<i class="fa fa-angle-right"></i>'.html_safe, edit_user_path(current_user), class: "account-item" %>
		</li>
		<li>
			<a class="notifications-item" href=""><i class="fa fa-exclamation-circle"></i>Notifications<i class="fa fa-angle-right"></i></a>
		</li>
		<li>
			<a class="help-item" href=""><i class="fa fa-question-circle"></i>Help<i class="fa fa-angle-right"></i></a>
		</li>
		<li>
			<%= link_to '<i class="fa fa-sign-out"></i>Sign Out<i class="fa fa-angle-right"></i>'.html_safe, logout_path, class: "signout-item", method: "delete" %>
		</li>
	</ul>
</div>

app/views/shared/dashboard/_current_user_info.html.erb
<div class="dashboard__sidebar--avatar-section">
	<div class="avatar-top">
		<%= link_to gravatar_for(current_user, size: 120), current_user %>
		<h1><%= current_user.name %></h1>
		<span><%= at_username current_user %></span>
	</div>
	<div class="avatar-bottom">
		<%= link_to(current_user, class: "avatar-bottom__stat") do %>
			<% if current_user.microposts.any? %>
				<h2><%= current_user.microposts.count %></h2>
			<% end %>
			<span>posts</span>
		<% end %>
		<% @user ||= current_user %>
		<a href="<%= following_user_path(@user) %>" class="avatar-bottom__stat">
			<h2><%= @user.following.count %></h2>
			<span>following</span>
		</a>
		<a href="<%= followers_user_path(@user) %>" class="avatar-bottom__stat">
			<h2><%= @user.followers.count %></h2>
			<span>followers</span>
		</a>
	</div>
</div>

app/views/shared/dashboard/_feed.html.erb
<div class="dashboard__content--feed-section">
	<div class="pagelet">
		<div class="pagelet__header"><i class="fa fa-rss"></i>Your Feed</div>
		<div class="pagelet__body">
		    <% if @feed_items.any? %>
			  	<ul class="posts-list">
			  		<%= sync_new partial: 'micropost', resource: @micropost %>
			  		<%= render @feed_items %>
			  	</ul>
			  <%= will_paginate @feed_items %>
			<% end %>
		</div>
	</div>
</div>

app/views/shared/dashboard/_post_widget.html.erb
<div class="dashboard__content--post-section">
	<div class="pagelet">
		<div class="pagelet__header"><i class="fa fa-pencil"></i>Post</div>
		<div class="pagelet__body">
			<%= form_for @micropost, html: { class: "post-section__form" } do |f| %>
				<%= render 'shared/error_messages', object: f.object %>
				<div class="post-section__form--group">
					<script>window.onbeforeunload = charCount();</script>
					<%= f.label :headline, 'Headline<span id="char-count__headline"></span>'.html_safe %>
					<%= f.text_field :headline %>
				</div>
				<div class="post-section__form--group">
					<div class="input-group">
						<%= f.label :date, "When?" %>
						<%= f.date_field :date %>
					</div>
					<div class="input-group where">
						<div class="input-group">
							<%= f.label :location, "Where?" %>
							<%= f.text_field :location %>
						</div>
						<a href="" class="btn btn__info"><i class="fa fa-map-marker"></i></a>
					</div>
				</div>
				<div class="post-section__form--group">
					<%= f.label :content, 'Your Story<span id="char-count__content"></span>'.html_safe %>
					<%= f.text_area :content, :rows => "3" %>
				</div>
				<%= f.submit "Post", class: "btn btn__primary btn__lg btn__post" %>
			<% end %>
		</div>
	</div>
</div>

app/views/shared/dashboard/_settings.html.erb
<div class="dashboard__content--settings">
	<div class="pagelet">
		<div class="pagelet__header"><i class="fa fa-cog"></i>Update Account</div>
		<div class="pagelet__body">
			<%= form_for @user, html: { class: "settings-form" } do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
				<div class="settings-form__section first">
					<h3><i class="fa fa-user"></i>Edit Account Credentials</h3>
					<div class="settings-form__section--group">
						<div class="input-group">
							<%= f.label :name %>
							<%= f.text_field :name, :placeholder => "Full Name" %>
						</div>
						<div class="input-group">
							<%= f.label :username %>
							<%= f.text_field :username %>
						</div>
					</div>
					<div class="settings-form__section--group">
						<%= f.label :email %>
						<%= f.text_field :email, :placeholder => "name@example.com" %>
					</div>
				</div>
				<div class="settings-form__section">
					<h3><i class="fa fa-lock"></i>Change Password <span>(must be 6 or more characters)</span></h3>
					<div class="settings-form__section--group">
						<div class="input-group">
							<%= f.label :password %>
							<%= f.password_field :password %>
						</div>
						<div class="input-group">
							<%= f.label :password_confirmation, "Confirm Password" %>
							<%= f.password_field :password_confirmation %>
						</div>
					</div>
				</div>
				<div class="settings-form__section">
					<h3><i class="fa fa-list-alt"></i>Edit Profile Info</h3>
					<div class="settings-form__section--group">
						<div class="input-group where">
							<div class="input-group">
								<%= f.label :user_location, "Where are you?" %>
								<%= f.text_field :user_location %>
							</div>
							<a href="" class="btn btn__info"><i class="fa fa-map-marker"></i></a>
						</div>
					</div>
					<div class="settings-form__section--group">
						<%= f.label :about_me, 'About Me<span class="character-count">160 char. left</span>'.html_safe %>
						<%= f.text_area :about_me, size: "3x3" %>
					</div>
					<div class="settings-form__section--group">
						<%= f.label :website, "Your Website" %>
						<%= f.text_field :website %>
					</div>
				</div>
				 <%= f.submit "Submit Changes", class: "btn btn__submit btn__lg btn__primary" %>
				 <div class="settings-form__section">
					 <h3><i class="fa fa-picture-o"></i>Change Profile Picture</h3>
					 <div class="settings-form__section--gravatar">
						<%= gravatar_for @user, size: "80" %>
						<a class="btn btn__info" href="http://gravatar.com/emails" target=_blank>Change</a>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/shared/dashboard/_user_info.html.erb
<div class="dashboard__sidebar--avatar-section">
	<div class="avatar-top">
		<%= link_to gravatar_for(@user, size: 120), @user %>
		<h1><%= @user.name %></h1>
		<span><%= at_username @user %></span>
	</div>
	<div class="avatar-bottom">
		<%= link_to(@user, class: "avatar-bottom__stat") do %>
			<% if @user.microposts.any? %>
				<h2><%= @user.microposts.count %></h2>
			<% end %>
			<span>posts</span>
		<% end %>
		<% @user ||= current_user %>
		<a href="<%= following_user_path(@user) %>" class="avatar-bottom__stat">
			<h2 id="following"><%= @user.following.count %></h2>
			<span>following</span>
		</a>
		<a href="<%= followers_user_path(@user) %>" class="avatar-bottom__stat">
			<h2 id="followers"><%= @user.followers.count %></h2>
			<span>followers</span>
		</a>
	</div>
</div>

app/views/shared/dashboard/_user_microposts.html.erb
<div class="dashboard__content--feed-section">
	<div class="pagelet">
		<div class="pagelet__header">
			<i class="fa fa-rss"></i><%= @user.username %>'s Feed</div>
		<div class="pagelet__body">
		    <% if @user.microposts.any? %>
		    	<ul class="posts-list">
		        	<%= render @user.microposts %>
		      	</ul>
		      	<%= will_paginate @microposts %>
		    <% end %>
		</div>
	</div>
</div>

app/views/shared/dashboard/_user_vitals.html.erb
<div class="dashboard__sidebar--vitals">
	<div class="pagelet">
		<div class="pagelet__header"><i class="fa fa-heart"></i><%= @user.username %>'s Vitals</div>
		<div class="pagelet__body">
			<% if @user.user_location %>
				<div class="vitals-item">
					<h6>Location</h6>
					<span><%= @user.user_location %></span>
				</div>
			<% end %>
			<% if @user.about_me %>
				<div class="vitals-item">
					<h6>About Me</h6>
					<span><%= @user.about_me %></span>
				</div>
			<% end %>
			<% if @user.website %>
				<div class="vitals-item">
					<h6>Website</h6>
					<span><%= @user.website %></span>
				</div>
			<% end %>
			<div class="vitals-item">
				<h6>Joined</h6>
				<span><%= (@user.created_at).strftime("%d %b %Y") %></span>
			</div>
		</div>
	</div>
</div>