config/routes.rb
Lemur::Application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  get "sessions/new"
  get "users/new"
  root 'static_pages#home'
  get 'about'	=> 'static_pages#about'
  get 'help'	=> 'static_pages#help'
  get 'terms'	=> 'static_pages#terms'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :show, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<div class="site-footer-push"></div>
<footer class="site-footer">
	<div class="site-footer-content">
		<div class="site-footer-content__column">
			<figure class="site-footer-content__column--logo">
				<figcaption><%= link_to "Lemur",   root_path %></figcaption>
				<%= link_to image_tag("global/logo.png", alt: "Lemur"), root_path %>
			</figure>
		</div>
		<div class="site-footer-content__column">
			<h5>About</h5>
			<ul>
				<li><%= link_to "About",   about_path %></li>
				<li><%= link_to "Terms",   terms_path %></li>
				<li><%= link_to "Help",   help_path %></li>
			</ul>
		</div>
		<div class="site-footer-content__column">
			<h5>Connect With Us</h5>
			<ul>
				<li><a href="#"><i class="fa fa-facebook"></i>Facebook</a></li>
				<li><a href="#"><i class="fa fa-twitter"></i>Twitter</a></li>
				<li><a href="#"><i class="fa fa-google-plus"></i>Google+</a></li>
			</ul>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="site-header">
	<div class="site-header-content">
		<div class="site-header-content__nav">
			<figure class="site-header-content__nav--logo">
				<%= link_to image_tag("global/logo.png", alt: "Lemur"), root_path %>
				<figcaption><%= link_to "Lemur",   root_path %></figcaption>
			</figure>
			<input type="checkbox" id="toggle" />
			<nav class="site-header-content__nav--menu">
				<label for="toggle" class="toggle" data-open="&#xf0c9;" data-close="&#xf00d;" onclick></label>
				<ul>
					<% if logged_in? %>
						<li><%= link_to "Post", root_path %></li>
						<li><%= link_to "Users", users_path %></li>
						<li><%= link_to "Sign Out", logout_path, method: "delete" %></li>
					<% else %>
						<li><%= link_to "About",   about_path %></li>
						<li><%= link_to "Terms",   terms_path %></li>
						<li><%= link_to "Help",   help_path %></li>
						<li><%= link_to "Sign In", login_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
		<% if current_page?(root_path) && !logged_in? %>
			<div class="site-header-content__callout">
				<h1>Get the word out!</h1>
				<p>Write about what's happening around you, post about upcoming events and more with Lemur.</p>
				<div class="site-header-content__callout--buttons">
					<%= link_to "Sign Up", signup_path, class: "btn btn__lg btn__primary" %>
					<%= link_to "Sign In", login_path, class: "btn btn__lg btn__primary" %>
				</div>
			</div>
			<div class="site-header-content__down-arrow">
				<a href="#home-feature__local"><%= embedded_svg "down.svg" %></a>
			</div>
		<% end %>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) %> | Lemur</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="//use.typekit.net/sia5kqm.js"></script>
	<script>try{Typekit.load();}catch(e){}</script>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= javascript_include_tag Sync.adapter_javascript_url %>
	<%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
	<main class="site-main<%= yield(:main_class_modifier) %>">
		<% flash.each do |message_type, message| %>
			<div class="alert alert__<%= message_type %>"><%= message %></div>
		<% end %>	
		<%= yield %>
	</main>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>